export const data={
 wait:{
  one:0,
  two:0,
  three:0,
  four:0,
  btn1:0,
  btn2:0,
  btn3:0,
  btn4:0,
  btn5:0
 },
 threeErrVideoSrc:'',
 four:{
  errVideoSrc:[],
  when:0
 },
 twoMoveBtnTime:{when:6,where:6.4},
 events:{
  'go':'.click,.pulse-btn'
 },
 view:{
  video:'.ov-video',
  el:{
   one:'.ov-wrap.vibrate.v1',
   two:'.ov-wrap.vibrate.v2',
   three:'.ov-wrap.vibrate.v3',
   four:'.ov-wrap.vibrate.v4',
   btn1:'.ov-wrap.vibrate.v1-1',
   btn2:'.ov-wrap.vibrate.v1-2',
   btn3:'.ov-wrap.vibrate.v1-3',
   btn4:'.ov-wrap.vibrate.v1-4',
   btn5:'.ov-wrap.vibrate.v1-5'
  },
  soundBg:{
   one:'.sounds[data-what=v1-bg]',
   two:'.sounds[data-what=v2-bg]',
   //three:'.sounds[data-what=v3-bg]'
   four:'.sounds[data-what=vibrate-v4-bg]'
  },
  shownCls:'shown',
  twoMoveBtnCls:'shifted',
  errCls:'incorr',
  hiddenCls:'hidden',
  startCls:'start',
  doneCls:'done',
  fourCls:['phase1','phase2']
 },
 button:{
  spread:100,
  timerDivider:39,
  wobbleDuration:{spread:1.5,shift:0.5},
  wobble:'.w-p-wrap',
  pText:'.w-p-p-text',
  pDiv:'.w-p-p div'
 }
};