export const data={
 wait:{
  one:30000,
  two:30000,
  three:30000
 },
 threeErrVideoSrc:'',
 twoMoveBtnTime:{when:6,where:6.4},
 events:{
  'go':'.click,.pulse-btn'
 },
 view:{
  video:'.ov-video',
  el:{
   one:'.ov-wrap.vibrate.v1',
   two:'.ov-wrap.vibrate.v2',
   three:'.ov-wrap.vibrate.v3'
  },
  soundBg:{
   one:'.sounds[data-what=v1-bg]',
   two:'.sounds[data-what=v2-bg]'
   //three:'.sounds[data-what=v3-bg]'
  },
  shownCls:'shown',
  twoMoveBtnCls:'shifted',
  errCls:'incorr',
  hiddenCls:'hidden',
  startCls:'start',
  doneCls:'done'
 },
 button:{
  spread:100,
  timerDivider:39,
  wobbleDuration:{spread:1.5,shift:0.5},
  wobble:'.w-p-wrap',
  pText:'.w-p-p-text',
  pDiv:'.w-p-p div'
 }
};