export const data={
 wait:3000000,
 winWait:1500,
 events:{
  'go':'.pulse-btn',
  'item':'.item',
  'click':'.click',
  'next':'.next'
 },
 view:{
  el:'.ov-wrap.photos',
  good:'.good',
  bad:'.bad',
  next:'.next',
  click:'.click',
  //soundBg:'.sounds[data-what=cartogr-bg]',
  okCls:'ok',
  doneCls:'done',
  shownCls:'shown'
 }
};