export const data={
 maxD:8,
 minSpeed:0.4,
 maxSpeed:10,
 minSh:5,
 maxSh:10,
 things:[{width:5,src:''},{width:8,src:'',no:true},{width:3,src:''}],
 events:{
  'click':'.pulse-btn'
 },
 view:{
  el:'.ov-wrap.catch',
  into:'.catch-block',
  thingCls:'thing',
  shownCls:'shown',
  startCls:'ok',
  noCls:'no'
 }
};